name: Build and test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run build

      - run: npm test
      - run: npm run test:e2e

      # for zip releases
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: built-dist-files
          path: dist/

      - uses: actions/upload-artifact@v4
        with:
          name: e2e-videos
          path: cypress/videos/
          if-no-files-found: ignore