describe('1+2+3+4÷5=2', () => {
    it('simple calculation', () => {
        cy.visit('/')
        cy.contains("1").click()
        cy.findByTestId("text-display").should("have.text", "I")
        cy.findAllByTestId("key-add").click()
        cy.contains("2").click()
        cy.findByTestId("key-add").click()
        cy.findByTestId("text-display").should("have.text", "III")
        cy.contains("3").click()
        cy.findByTestId("key-add").click()
        cy.findByTestId("text-display").should("have.text", "VI")
        cy.contains("4").click()
        cy.findByTestId("key-divide").click()
        cy.findByTestId("text-display").should("have.text", "X")
        cy.contains("5").click()
        cy.findByTestId("key-equals").click()
        cy.findByTestId("text-display").should("have.text", "II")
    })
})