@startuml
left to right direction
skinparam packageStyle rectangle
actor "System" as System
actor "Registered User" as User
actor "Database" as DB

package "Activity & Progress Tracking System" {
    ' Registered User UseCases
    actor "Registered User" as User
    usecase "Log Activity" as UC1
    usecase "View Progress and Statistics" as UC2
    usecase "Set Goals" as UC3

    ' System UseCases
    usecase "Generate Statistics" as UC4
    usecase "Manage User Data" as UC5

    User --> UC1
    User --> UC2
    User --> UC3

    System --> UC4
    System <--> UC5
    System <..> DB : "access and store user data"

    UC4 ..> UC2 : "provides statistics for"
    UC1 ..> UC5 : "stores activity data in"
    UC3 ..> UC5 : "saves in"


}

@enduml
